HW04
DenKuzin33/OtusHw pull request #4
Opened 2023-05-14 15:00 UTC by DenKuzin33

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-05-15 11:01 UTC, engineer-go requested changes
Хорошее решение, но предлагаю его немного оптимизировать, чтобы сократить и сделать понятнее.

2023-05-15 11:01 UTC, engineer-go commented on hw04_lru_cache/list.go
> +	list.first = item
вот тут можно упросить функцию, т.к. это фактически комбинация remove + pushFront

2023-05-15 11:01 UTC, engineer-go commented on hw04_lru_cache/list.go
> +	list.length--
Какое тут будет поведение, если мы приняли len(list) == 0 ?

2023-05-15 11:01 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Вряд ли вы будете перезаписывать capacity при вызове clear, имхо тут это лишнее

2023-05-15 11:01 UTC, engineer-go commented on hw04_lru_cache/list.go
> +	PushBack(key Key, v interface{}) *ListItem
А зачем вот эти изменения?

2023-05-15 11:01 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +		delete(cache.items, back.Key)
А зачем нам нужно получать дополнительно key из `back.key` если мы уже знаем его из параметров?

2023-05-15 15:04 UTC, DenKuzin33 commented on hw04_lru_cache/list.go
> +	list.first = item
Здесь не соглашусь, ведь remove + pushFront отправит в мусор один объект и выделит память под другой такой же. MoveToFront же просто переставит указатели.

2023-05-15 15:11 UTC, DenKuzin33 commented on hw04_lru_cache/list.go
> +	list.length--
В задании есть пункт "Считаем, что методы Remove и MoveToFront вызываются только от существующих в списке элементов". То есть, такой кейс невозможен, если я правильно понимаю.

2023-05-15 15:16 UTC, DenKuzin33 commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Не очень понял. Если не задать capacity мы же ничего в кеш не сможем положить, так как там 0 окажется.

2023-05-15 15:19 UTC, DenKuzin33 commented on hw04_lru_cache/cache.go
> +		delete(cache.items, back.Key)
Так это же разные ключи: ключ из параметра для вставки/обновления элемента, а back.key для удаления последнего элемента при переполнении кеша.

2023-05-15 15:22 UTC, DenKuzin33 commented on hw04_lru_cache/list.go
> +	PushBack(key Key, v interface{}) *ListItem
Для удаления элемента из cache.items при переполнении кеша. Его ключ ведь никак иначе вычислить нельзя без полного обхода мапы. А так он просто лежит в самом ListItem, который мы получаем вызовом Back().

2023-05-15 15:45 UTC, itiulkanov commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Почему? Мы же не новый объект передаём, а существующий, я так понимаю

2023-05-15 15:49 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
А мы clear не от существующего элемента разве вызываем?

2023-05-15 16:07 UTC, DenKuzin33 commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Нет, от экземпляра самого кеша, мы же из него удаляем элементы.

2023-05-16 13:00 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Ок, а в экземпляре кеша capacity не задан, получается? Почему он 0, если мы его при инициализации уже задали?

2023-05-16 13:20 UTC, engineer-go commented on hw04_lru_cache/list.go
> +	PushBack(key Key, v interface{}) *ListItem
Согласен, что нам нужен ключ, но мы его можем хранить в том же value, т.к. оно само по себе принимает что угодно, не меняя контракт.

2023-05-16 13:20 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		delete(cache.items, back.Key)
Ага, это уже я туплю, точно.

2023-05-16 18:03 UTC, DenKuzin33 commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Задан, но мы же здесь новый экземпляр создаем и перекидываем на него указатель cache. Иначе сложности O(1) не добьемся

2023-05-16 18:21 UTC, DenKuzin33 commented on hw04_lru_cache/list.go
> +	PushBack(key Key, v interface{}) *ListItem
Можно конечно, но непонятен смысл. PushFront и PushBack все равно будут завязаны на пару ключ-значение. Только при таком подходе нужен новый тип, к которому будет приводиться интерфейс, а это как минимум очень неочевидно при вызове методов и скорее всего медленнее. Плюс нужны будут проверки типов, что тоже понизит читаемость.

2023-05-16 19:13 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	PushBack(key Key, v interface{}) *ListItem
Соглашусь с тем что читаемость падает. Просто уже привык видеть что все стараются не трогать заготовки и оставлять как есть, и тоже уже рассматривать начал это как некий контракт. Ок, тогда не вижу смысла что то менять, одобряю.

2023-05-16 19:20 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
_сложности O(1) не добьемся_ не понимаю почему? Мы вызвали clear на объекте, обнулили 2 из 3х его полей, вызовами new и make, capacity осталась неизменной

2023-05-17 12:04 UTC, DenKuzin33 commented on hw04_lru_cache/cache.go
> +		capacity: cache.capacity,
Не про то подумал изначально. Метод сократил

2023-05-17 12:59 UTC, engineer-go approved these changes
Всё отлично, аппрувнул

2023-05-18 07:42 UTC, merged